services:
  db:
    build:
      context: .
      dockerfile: dockerfile-postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/code/translation-database-data/${ENVNAME}:/var/lib/postgresql/data
    env_file:
      - env-files/postgres.env
      - .env
  app:
    build:
      context: .
      dockerfile: dockerfile-django
    ports:
      - "8080:8080"
    env_file:
      - env-files/django.env
      - env-files/postgres.env
      - .env
