services:
  db:
    image: postgres:15.5
    ports:
      - "5432:5432"
    volumes:
      - ~/code/translation-database-data:/var/lib/postgresql/data
      # Do this with ansible or other deploy software in final version
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  app:
    build:
      context: .
      dockerfile: django-dockerfile
    ports:
      - "8080:8080"
