FROM python:3.12.1

COPY app /app
# COPY .env /app/.env
COPY requirements.txt /tmp/requirements.txt
COPY entrypoint.sh /tmp/entrypoint.sh

RUN ["chmod", "+x", "/tmp/entrypoint.sh"]

RUN pip install --upgrade pip
RUN pip install -r /tmp/requirements.txt

CMD ["/tmp/entrypoint.sh"]
