# Generated by Django 4.2.9 on 2024-02-17 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Original_Text',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=10000)),
                ('extra_info', models.CharField(blank=True, max_length=10000)),
                ('status', models.IntegerField(choices=[(0, '下書き'), (1, '対応待ち'), (2, '翻訳中'), (3, '翻訳済み')], default=0)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated_datetime', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Translated_Text',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=10000)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_updated_datetime', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('original_text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.original_text')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
