# Generated by Django 4.2.9 on 2024-01-03 16:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Translated_Texts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('translated_text', models.CharField(max_length=10000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.users')),
            ],
        ),
        migrations.CreateModel(
            name='Original_Texts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_text', models.CharField(max_length=10000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translations.users')),
            ],
        ),
    ]
