# Generated by Django 4.2.9 on 2024-02-22 08:34

from django.conf import settings
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Original_Text',
            new_name='OriginalText',
        ),
        migrations.RenameModel(
            old_name='Translated_Text',
            new_name='TranslatedText',
        ),
        migrations.AlterModelManagers(
            name='originaltext',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
