# Generated by Django 4.2.9 on 2024-01-04 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='original_text',
            name='last_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='translated_text',
            name='last_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='translated_text',
            name='original_text_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='translations.original_text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='date created'),
        ),
    ]
