# Generated by Django 4.2.9 on 2024-02-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_rename_original_text_originaltext_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='originaltext',
            managers=[
            ],
        ),
    ]
