# Generated by Django 4.2.9 on 2024-01-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0003_rename_text_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='original_text',
            name='extra_info',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='original_text',
            name='status',
            field=models.IntegerField(choices=[(0, '下書き'), (1, '対応待ち'), (2, '翻訳中'), (3, '翻訳済み')], default=0),
        ),
    ]
