# Generated by Django 4.2.9 on 2024-02-22 09:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translations', '0004_rename_original_text_id_translatedtext_originaltext_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OriginalText',
            new_name='Original',
        ),
        migrations.RenameModel(
            old_name='TranslatedText',
            new_name='Translation',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='originaltext_id',
            new_name='original_id',
        ),
    ]
