# Generated by Django 4.2.9 on 2024-02-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0005_rename_originaltext_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original',
            name='last_updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
    ]
